apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s0jztbdqp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s0jztbdqp-nodejs 
  name: s0jztbdqp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: s0jztbdqp-nodejs 
