apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s0jztbdqp-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/s0jztbdqp-nodejs-gitops